name: Build and Publish to GitHub Packages

on:
    push:
        branches:
            - master
        tags:
            - 'v*'

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22
                  registry-url: https://npm.pkg.github.com/
                  scope: '@yirmelsanchez'

            - name: Install dependencies
              run: npm ci

            - name: Build (includes tests)
              run: npm run build

            - name: Publish to GitHub Packages
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
